FirstView:

<FirstView>: 
    BoxLayout:
        orientation: "vertical"
        AnchorLayout: 
            size_hint: 1,1
            anchor_y: "top"
            anchor_x: "center"
            padding: [dp(0),dp(20),dp(0),dp(0)]  
            Button:
                text: 'First View Button'
                on_press: root.get_file()
                size_hint: 0.5, None
                height: dp(20)
                pos_hint:{'center_x':0.5, 'center_y':0.5}
                